# Generated by Django 6.0 on 2026-01-02 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rollover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('currency', models.CharField(default='GHS', max_length=8)),
                ('initial_stake', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_odds', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reinvest_pct', models.PositiveIntegerField(default=100)),
                ('total_rounds', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='active', max_length=12)),
                ('current_bankroll', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolloverRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('planned_stake', models.DecimalField(decimal_places=2, max_digits=12)),
                ('planned_odds', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pick_type', models.CharField(choices=[('result_home', 'result_home'), ('result_draw', 'result_draw'), ('result_away', 'result_away'), ('dc_1x', 'dc_1x'), ('dc_x2', 'dc_x2'), ('goals_over_0_5', 'goals_over_0_5'), ('goals_over_1_5', 'goals_over_1_5'), ('goals_even', 'goals_even')], default='result_home', max_length=24)),
                ('pick_label', models.CharField(blank=True, max_length=200)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('won', 'won'), ('lost', 'lost'), ('void', 'void'), ('skipped', 'skipped')], default='pending', max_length=12)),
                ('actual_stake', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('return_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bankroll_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rollover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='rollover.rollover')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('rollover', 'number')},
            },
        ),
    ]
