# Generated by Django 6.0 on 2026-01-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollover', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolloverround',
            name='pick_label',
        ),
        migrations.AddField(
            model_name='rolloverround',
            name='games_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
